# Use the official Node.js image as the base image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files to install dependencies
COPY ./express-app/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ./express-app .

# Expose the port that Express will listen on
EXPOSE 3001
