version: '3'

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile.express
    working_dir: /app
    volumes:
      - ./express-app:/app
    ports:
      - "3000:3000"
    networks:
      - my-network
    command: npm start

  envoy-proxy:
    build:
      context: .
      dockerfile: Dockerfile.envoy
    volumes:
      - ./.:/etc/envoy
      - ./certs:/etc/certs
    ports:
      - "8443:8443"
      - "9901:9901"
    networks:
      - my-network
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--service-cluster", "envoy", "--log-level", "debug"]
    depends_on:
      - express-app

networks:
  my-network:
    driver: bridge
